### ISSUE TITLE
[guide] How to install on HP laptop

### ISSUE THREAD

**Issue by charles8191** [pbatard/Mosby#1]
I am using an HP Laptop 15-dy5000 series laptop here, but should work on similar Alder Lake HP laptops.

Firstly, reboot into the BIOS by pressing F10. When asked to save & quit answer No. Go into Boot Options and turn off Secure Boot, then clear the keys. Then press F10 again and save changes. Reboot to your UEFI Shell USB using the F9 key and run Mosby like usual. After that, reenable secure boot. Now you should be all set and the platform key should say enrolled while enabling Secure Boot.

**Comment by pbatard** [comment]
Thanks for the report. Deleting the keys is a well known method of resetting Secure Boot to Setup Mode, and this is [something we mention in the various help screens we provide if we detect that the user has trouble entering Setup Mode](https://github.com/pbatard/Mosby/blob/bde307b92d7fe74bc870fb26b34535b4ae92b580/src/variables.c#L74-L76).

As such I will close this issue.

**Comment by lollita** [comment]
I tryed in HP ZBook G1 but I get Unsupported or incomplete parameter '|.
Do it is not possibile to use Mosby here?
